services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Teebay_Zahin
    ports:
      - "5011:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure:2

  backend:
    build:
      context: ./backend
    ports:
      - "5010:5010"
    environment:
      - JWT_SECRET=xhpioafpe
      - APP_PORT=5010
      - JWT_EXPIRES_IN=20d
      - DATABASE_URL=postgresql://postgres:1234@db:5432/Teebay_Zahin?schema=public
    depends_on:
      - db
    restart: on-failure:2

  frontend:
    build:
      context: ./frontend
    ports:
      - "5179:5179"
    environment:
      - VITE_SERVER_ENDPOINT=http://localhost:5010
    depends_on:
      - backend
    restart: on-failure:2

volumes:
  pgdata:
